+ python train_lgnn_fflow.py --n-nodes 10 --n-graphs 1 --gpu 0 --verbose --q 4
Traceback (most recent call last):
  File "train_lgnn_fflow.py", line 186, in <module>
    loss, overlap, t_forward, t_backward = step(i, j, adj_diag_deg_inverse, diag_deg_inverse_adj_deg_inverse, adj_diag_lg_deg_inverse, pm, pd, deg_g, deg_lg)
  File "train_lgnn_fflow.py", line 101, in wrap
    return f(*new)
  File "train_lgnn_fflow.py", line 113, in step
    z = model(g_a_d, g_d_a_d, lg_a_d, pm, pd, deg_g, deg_lg)
  File "/home/lc3909/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lc3909/dgl/examples/pytorch/line_graph/lgnn_fflow.py", line 103, in forward
    x, y = module(x, y, g_a_d, g_d_a_d, lg_a_d, pm, pd)
  File "/home/lc3909/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lc3909/dgl/examples/pytorch/line_graph/lgnn_fflow.py", line 55, in forward
    x = self.bn_x(x.unsqueeze(2).unsqueeze(3)).squeeze(3).squeeze(2)
  File "/home/lc3909/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lc3909/miniconda3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 76, in forward
    exponential_average_factor, self.eps)
  File "/home/lc3909/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1623, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: running_mean should contain 5 elements not 8
